http://localhost:8080/api/books

###

http://localhost:8080/api/books/633bccbde8223018daf0917b
###

DELETE http://localhost:8080/api/books/633bcde8223018daf0917b
###

POST http://localhost:8080/api/books
Content-Type: application/json

{
    "title": "",
    "description": "test",
    "comment": "",
    "rating": 4
}

###

PATCH http://localhost:8080/api/books/67f2183bd82c3be5aef1a047
Content-Type: application/json

{
    "title": "",
    "rating": 3
}